// Comprehensive Exercise Database - 400+ Exercises
export const EXERCISE_SEED_DATA = [
  // CHEST EXERCISES
  { name: 'Barbell Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Retract shoulder blades and arch upper back slightly\n2. Grip slightly wider than shoulder width\n3. Lower bar to mid-chest with control\n4. Drive feet into floor for stability\n5. Press up in a slight arc back toward the rack' },
  { name: 'Incline Barbell Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Set bench to 30-45 degree angle\n2. Grip slightly wider than shoulder width\n3. Lower bar to upper chest/collarbone area\n4. Keep shoulder blades retracted\n5. Press up without flaring elbows excessively' },
  { name: 'Incline Dumbbell Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Set bench to 30-45 degree angle\n2. Grip slightly wider than shoulder width\n3. Lower bar to upper chest/collarbone area\n4. Keep shoulder blades retracted\n5. Press up without flaring elbows excessively' },
  { name: 'Decline Barbell Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Start with dumbbells at chest level, palms facing forward\n2. Retract shoulder blades into the bench\n3. Press up and slightly inward\n4. Keep a slight arch in your upper back\n5. Lower with control — 2-3 seconds down' },
  { name: 'Incline Dumbbell Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Set bench to 30-45 degrees\n2. Start with dumbbells at shoulder height\n3. Press up and slightly inward\n4. Focus on squeezing upper chest at the top\n5. Lower slowly with elbows at 45 degrees' },
  { name: 'Decline Dumbbell Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Dumbbell Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Start with arms extended above chest, slight bend in elbows\n2. Lower arms out to the sides in a wide arc\n3. Feel a deep stretch in the chest at the bottom\n4. Squeeze chest to bring dumbbells back together\n5. Keep the same elbow bend throughout' },
  { name: 'Incline Dumbbell Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Cable Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable', tips: '1. Set cables at shoulder height or slightly above\n2. Step forward with one foot for stability\n3. Bring hands together in front of chest\n4. Squeeze chest hard at the peak contraction\n5. Control the return — don\'t let cables pull you back' },
  { name: 'Push-Ups', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Bodyweight', tips: '1. Hands slightly wider than shoulder width\n2. Keep body in a straight line from head to heels\n3. Lower chest toward the floor\n4. Keep core tight throughout\n5. Press up fully, extending arms without locking elbows' },
  { name: 'Wide Grip Push-Ups', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Diamond Push-Ups', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Decline Push-Ups', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Chest Dips', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight', tips: '1. Lean forward about 30 degrees\n2. Lower until upper arms are parallel to floor\n3. Keep elbows slightly flared to target chest\n4. Push up by squeezing your chest\n5. Don\'t go too deep if you have shoulder issues' },
  { name: 'Pec Deck Machine', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Chest Press Machine', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Machine', tips: '1. Adjust seat so handles are at chest level\n2. Sit with back flat against the pad\n3. Push handles forward without locking elbows\n4. Squeeze chest at full extension\n5. Return slowly with control' },
  { name: 'Smith Machine Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Landmine Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Svend Press', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Plate' },
  { name: 'Cable Crossover', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Cable' },
  { name: 'Decline Cable Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable', tips: '1. Set cables at shoulder height or slightly above\n2. Step forward with one foot for stability\n3. Bring hands together in front of chest\n4. Squeeze chest hard at the peak contraction\n5. Control the return — don\'t let cables pull you back' },

  // BACK EXERCISES
  { name: 'Deadlift', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Barbell', tips: '1. Stand with feet hip-width apart, bar over mid-foot\n2. Hinge at hips and grip bar just outside knees\n3. Flatten back, brace core, chest up\n4. Drive through floor, keeping bar close to body\n5. Lock out at top — squeeze glutes, stand tall' },
  { name: 'Romanian Deadlift', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Start standing with bar at hip level\n2. Push hips back while keeping knees slightly bent\n3. Lower bar along thighs until you feel a hamstring stretch\n4. Keep back flat and core braced throughout\n5. Drive hips forward to return to standing' },
  { name: 'Sumo Deadlift', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Barbell Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Hinge forward to about 45 degrees\n2. Grip bar slightly wider than shoulder width\n3. Pull bar toward lower chest/upper abs\n4. Squeeze shoulder blades together at the top\n5. Lower with control — don\'t let the bar drop' },
  { name: 'Pendlay Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'T-Bar Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Single Arm Dumbbell Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Chest Supported Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Pull-Ups', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Bodyweight', tips: '1. Grip bar slightly wider than shoulder width\n2. Start from a dead hang with arms fully extended\n3. Pull up by driving elbows down and back\n4. Chin should clear the bar at the top\n5. Lower slowly with control to full extension' },
  { name: 'Chin-Ups', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Wide Grip Pull-Ups', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Neutral Grip Pull-Ups', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Lat Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Machine', tips: '1. Grip bar slightly wider than shoulder width\n2. Lean back slightly (10-15 degrees)\n3. Pull bar to upper chest, leading with elbows\n4. Squeeze lats at the bottom of the movement\n5. Return slowly — feel the stretch at the top' },
  { name: 'Wide Grip Lat Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Close Grip Lat Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Seated Cable Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Face Pulls', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Straight Arm Pulldown', target_muscle: 'Back', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Rack Pulls', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Hyperextensions', target_muscle: 'Back', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Good Mornings', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Inverted Rows', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'One Arm Half Kneeling Pull Down', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },

  // SHOULDER EXERCISES
  { name: 'Overhead Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Grip bar just outside shoulder width\n2. Start with bar at collarbone level\n3. Brace core and press straight overhead\n4. Move head forward slightly as bar passes face\n5. Lock out at the top with bar over mid-foot' },
  { name: 'Military Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Push Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Dumbbell Shoulder Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Start with dumbbells at shoulder height, palms facing forward\n2. Press dumbbells overhead in a slight arc\n3. Don\'t lock out elbows completely\n4. Lower slowly to shoulder height\n5. Keep core braced and avoid arching back' },
  { name: 'Seated Dumbbell Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Arnold Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Dumbbell', tips: '1. Start with palms facing you at chin level\n2. Rotate palms outward as you press up\n3. At the top, palms should face forward\n4. Reverse the rotation on the way down\n5. Keep the movement smooth and controlled' },
  { name: 'Lateral Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Stand with slight forward lean\n2. Raise arms out to the sides to shoulder height\n3. Lead with elbows, not hands\n4. Pinky up slightly at the top for better activation\n5. Lower slowly — don\'t just drop the weight' },
  { name: 'Front Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Rear Delt Flyes', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Cable Lateral Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Cable Front Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Reverse Pec Deck', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Upright Rows', target_muscle: 'Shoulders', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Shrugs', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Barbell Shrugs', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Pike Push-Ups', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Handstand Push-Ups', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Machine Shoulder Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Reverse Cable Crossover', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Behind The Back Cable Lateral Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },

  // ARMS - BICEPS
  { name: 'Barbell Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Barbell', tips: '1. Stand with feet shoulder-width apart\n2. Grip bar at shoulder width, palms up\n3. Keep elbows pinned to your sides\n4. Curl up squeezing the biceps at the top\n5. Lower slowly — no swinging' },
  { name: 'EZ Bar Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Preacher Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Barbell', tips: '1. Rest upper arms flat on the pad\n2. Start with arms almost fully extended\n3. Curl up, squeezing at the top\n4. Lower slowly — don\'t drop the weight\n5. Don\'t lean back to cheat the weight up' },
  { name: 'Dumbbell Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Hammer Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Hold dumbbells with palms facing each other\n2. Keep elbows pinned at your sides\n3. Curl up without rotating the wrist\n4. Squeeze at the top for 1 second\n5. Lower with control' },
  { name: 'Incline Dumbbell Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Concentration Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Cable Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Cable Hammer Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Spider Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Zottman Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: '21s Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Preacher Hammer Curls', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Rest upper arms flat on the pad\n2. Start with arms almost fully extended\n3. Curl up, squeezing at the top\n4. Lower slowly — don\'t drop the weight\n5. Don\'t lean back to cheat the weight up' },
  { name: 'Machine Preacher Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Machine', tips: '1. Rest upper arms flat on the pad\n2. Start with arms almost fully extended\n3. Curl up, squeezing at the top\n4. Lower slowly — don\'t drop the weight\n5. Don\'t lean back to cheat the weight up' },

  // ARMS - TRICEPS
  { name: 'Close Grip Bench Press', target_muscle: 'Triceps', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Tricep Dips', target_muscle: 'Triceps', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight', tips: '1. Keep torso upright (not leaning forward)\n2. Lower until upper arms are parallel to floor\n3. Keep elbows close to body\n4. Push up by extending arms fully\n5. Don\'t go too deep to avoid shoulder strain' },
  { name: 'Overhead Tricep Extension', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Skull Crushers', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Lie on bench, arms extended above shoulders\n2. Lower bar toward forehead by bending elbows\n3. Keep upper arms stationary\n4. Extend arms back to starting position\n5. Don\'t flare elbows — keep them narrow' },
  { name: 'Tricep Pushdown', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable', tips: '1. Stand facing the cable machine\n2. Grip bar with palms down, elbows at sides\n3. Push down until arms are fully extended\n4. Squeeze triceps at the bottom\n5. Return slowly — don\'t let the cable pull your hands up' },
  { name: 'Rope Pushdown', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Overhead Cable Extension', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Tricep Kickbacks', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Diamond Push-Ups', target_muscle: 'Triceps', category: 'Push', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Dumbbell Skull Crushers', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Bench Dips', target_muscle: 'Triceps', category: 'Push', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Single Arm Cable Pushdown  ', target_muscle: 'Triceps', category: 'Push', difficulty: 'Beginner', equipment: 'Cable', tips: '1. Stand facing the cable machine\n2. Grip bar with palms down, elbows at sides\n3. Push down until arms are fully extended\n4. Squeeze triceps at the bottom\n5. Return slowly — don\'t let the cable pull your hands up' },
  { name: 'Single Arm Overhead Tricep Extension', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  // LEGS - QUADRICEPS
  { name: 'Barbell Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Bar on upper traps, feet shoulder-width apart\n2. Brace core and push hips back\n3. Squat down until thighs are parallel or below\n4. Keep knees tracking over toes\n5. Drive up through heels, keeping chest up' },
  { name: 'Front Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Goblet Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell', tips: '1. Hold dumbbell vertically at chest level\n2. Feet slightly wider than shoulder width\n3. Squat down between your legs\n4. Keep elbows inside knees\n5. Drive up through full foot' },
  { name: 'Bulgarian Split Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Dumbbell', tips: '1. Rear foot elevated on bench behind you\n2. Front foot about 2 feet from bench\n3. Lower until front thigh is parallel to floor\n4. Keep torso upright\n5. Push up through the front heel' },
  { name: 'Leg Press', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Machine', tips: '1. Place feet shoulder-width on the platform\n2. Lower weight until knees are at 90 degrees\n3. Don\'t lock knees at the top\n4. Keep lower back flat against the pad\n5. Push through full foot, not just toes' },
  { name: 'Hack Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Leg Extension', target_muscle: 'Quadriceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine', tips: '1. Adjust pad so it sits on lower shins\n2. Keep back flat against the seat\n3. Extend legs fully, squeezing quads at top\n4. Lower slowly with control\n5. Don\'t use momentum — controlled reps only' },
  { name: 'Walking Lunges', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Reverse Lunges', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Step-Ups', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Sissy Squat', target_muscle: 'Quadriceps', category: 'Isolation', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Box Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell' },

  // LEGS - HAMSTRINGS
  { name: 'Romanian Deadlift', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Stiff Leg Deadlift', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Lying Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Seated Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Nordic Curls', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Good Mornings', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Single Leg RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Glute Ham Raise', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Advanced', equipment: 'Machine' },

  // LEGS - GLUTES
  { name: 'Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell', tips: '1. Upper back against bench, feet flat on floor\n2. Bar across hips with pad\n3. Drive hips up until body forms a straight line\n4. Squeeze glutes hard at the top\n5. Lower with control — don\'t just drop' },
  { name: 'Glute Bridge', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Single Leg Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Cable Pull Through', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Kickbacks', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Sumo Deadlift', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },

  // LEGS - CALVES
  { name: 'Standing Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Seated Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Donkey Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Single Leg Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },

  // CORE/ABS
  { name: 'Crunches', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight', tips: '1. Lie on back with knees bent, feet flat\n2. Hands behind head — don\'t pull on neck\n3. Lift shoulders off floor using abs\n4. Exhale as you crunch up\n5. Lower slowly with control' },
  { name: 'Bicycle Crunches', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Plank', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight', tips: '1. Forearms on floor, body in straight line\n2. Engage core — pull belly button to spine\n3. Don\'t let hips sag or pike up\n4. Keep breathing normally — don\'t hold breath\n5. Squeeze glutes for extra stability' },
  { name: 'Side Plank', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Russian Twists', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Leg Raises', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Hanging Leg Raises', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Mountain Climbers', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Ab Wheel Rollout', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Equipment' },
  { name: 'Cable Crunches', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Decline Sit-Ups', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Dragon Flag', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Hollow Body Hold', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Dead Bug', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Bird Dog', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Pallof Press', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Windshield Wipers', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'L-Sit', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Bodyweight' },

  // OLYMPIC LIFTS & COMPOUND
  { name: 'Clean and Jerk', target_muscle: 'Full Body', category: 'Olympic', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Snatch', target_muscle: 'Full Body', category: 'Olympic', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Power Clean', target_muscle: 'Full Body', category: 'Olympic', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Hang Clean', target_muscle: 'Full Body', category: 'Olympic', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Clean and Press', target_muscle: 'Full Body', category: 'Olympic', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Thruster', target_muscle: 'Full Body', category: 'Crossfit', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Burpees', target_muscle: 'Full Body', category: 'Cardio', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Box Jumps', target_muscle: 'Full Body', category: 'Plyometric', difficulty: 'Intermediate', equipment: 'Equipment' },
  { name: 'Kettlebell Swings', target_muscle: 'Full Body', category: 'Crossfit', difficulty: 'Beginner', equipment: 'Kettlebell' },
  { name: 'Turkish Get-Up', target_muscle: 'Full Body', category: 'Crossfit', difficulty: 'Advanced', equipment: 'Kettlebell' },
  { name: 'Farmers Walk', target_muscle: 'Full Body', category: 'Strongman', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Sled Push', target_muscle: 'Full Body', category: 'Strongman', difficulty: 'Intermediate', equipment: 'Equipment' },
  { name: 'Sled Pull', target_muscle: 'Full Body', category: 'Strongman', difficulty: 'Intermediate', equipment: 'Equipment' },
  { name: 'Battle Ropes', target_muscle: 'Full Body', category: 'Cardio', difficulty: 'Beginner', equipment: 'Equipment' },

  // ADDITIONAL VARIATIONS - Chest
  { name: 'Close Grip Dumbbell Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Reverse Grip Bench Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Incline Smith Machine Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Decline Smith Machine Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Low Cable Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'High Cable Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Single Arm Cable Flyes', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Cable' },
  { name: 'Plate Squeeze Press', target_muscle: 'Chest', category: 'Isolation', difficulty: 'Beginner', equipment: 'Plate' },
  { name: 'Floor Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Spoto Press', target_muscle: 'Chest', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },

  // ADDITIONAL VARIATIONS - Back
  { name: 'Meadows Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Seal Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Helms Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Kroc Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Dumbbell' },
  { name: 'Machine Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Underhand Barbell Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Yates Row', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Pullover', target_muscle: 'Back', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Deficit Deadlift', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Snatch Grip Deadlift', target_muscle: 'Back', category: 'Pull', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Single Arm Lat Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Intermediate', equipment: 'Cable' },
  { name: 'Reverse Grip Lat Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'V-Bar Pulldown', target_muscle: 'Back', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },

  // ADDITIONAL VARIATIONS - Shoulders
  { name: 'Bradford Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Z Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Viking Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Single Arm Dumbbell Press', target_muscle: 'Shoulders', category: 'Push', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Bus Driver', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Plate' },
  { name: 'Cuban Press', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Scarecrow', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Y Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Lu Raises', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Advanced', equipment: 'Plate' },
  { name: 'Prone Incline Lateral Raise', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Cable Upright Row', target_muscle: 'Shoulders', category: 'Pull', difficulty: 'Intermediate', equipment: 'Cable' },
  { name: 'Trap Bar Shrugs', target_muscle: 'Shoulders', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Barbell' },

  // ADDITIONAL VARIATIONS - Arms
  { name: 'Close Grip EZ Bar Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Wide Grip EZ Bar Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Reverse Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Drag Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Bayesian Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Cable' },
  { name: 'Cross Body Hammer Curl', target_muscle: 'Biceps', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Waiter Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Machine Curl', target_muscle: 'Biceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'JM Press', target_muscle: 'Triceps', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'California Press', target_muscle: 'Triceps', category: 'Push', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Tate Press', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Single Arm Overhead Extension', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Single Arm Pushdown', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Reverse Grip Pushdown', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'V-Bar Pushdown', target_muscle: 'Triceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Weighted Dips', target_muscle: 'Triceps', category: 'Push', difficulty: 'Advanced', equipment: 'Bodyweight' },

  // ADDITIONAL VARIATIONS - Legs
  { name: 'Pause Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Pin Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Safety Bar Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Zercher Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Anderson Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Hatfield Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Advanced', equipment: 'Barbell' },
  { name: 'Spanish Squat', target_muscle: 'Quadriceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Heels Elevated Goblet Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Landmine Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Belt Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Smith Machine Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Single Leg Press', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Narrow Stance Leg Press', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Wide Stance Leg Press', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Curtsy Lunge', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Deficit Reverse Lunge', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Barbell Lunge', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Step Up', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Barbell Step Up', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Hack Squat Machine', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Pendulum Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'V Squat', target_muscle: 'Quadriceps', category: 'Legs', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Leg Extension Drop Set', target_muscle: 'Quadriceps', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Single Leg Extension', target_muscle: 'Quadriceps', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Dumbbell RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Trap Bar RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Kettlebell RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Beginner', equipment: 'Kettlebell' },
  { name: 'Cable Pull Through RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'B Stance RDL', target_muscle: 'Hamstrings', category: 'Pull', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Reverse Hyper', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Swiss Ball Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Slider Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Standing Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Cable Leg Curl', target_muscle: 'Hamstrings', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Barbell Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Dumbbell Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Smith Machine Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Banded Hip Thrust', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Frog Pump', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Cable Glute Kickback', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Smith Machine Glute Kickback', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Dumbbell Glute Bridge', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Single Leg Glute Bridge', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Elevated Glute Bridge', target_muscle: 'Glutes', category: 'Legs', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Abductor Machine', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Adductor Machine', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Copenhagen Plank', target_muscle: 'Glutes', category: 'Isolation', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Calf Press on Leg Press', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Dumbbell Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Barbell Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Smith Machine Calf Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Machine' },
  { name: 'Tibialis Raise', target_muscle: 'Calves', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },

  // ADDITIONAL CORE
  { name: 'Weighted Crunch', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Plate' },
  { name: 'Reverse Crunch', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Toe Touches', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'V-Ups', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Tuck Crunch', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Jack Knife Sit-Up', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Weighted Plank', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Plate' },
  { name: 'Plank to Pike', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Plank Jacks', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Plank Up-Downs', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Copenhagen Side Plank', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Weighted Russian Twist', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Plate' },
  { name: 'Medicine Ball Slam', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Equipment' },
  { name: 'Woodchopper', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Oblique Crunch', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Side Bend', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Landmine Rotation', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Barbell' },
  { name: 'Hanging Knee Raise', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Captains Chair Leg Raise', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Machine' },
  { name: 'Decline Leg Raise', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Bodyweight' },
  { name: 'Flutter Kicks', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Scissor Kicks', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Starfish Crunch', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Suitcase Carry', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Overhead Carry', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Waiter Walk', target_muscle: 'Abs', category: 'Core', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Turkish Get-Up', target_muscle: 'Abs', category: 'Core', difficulty: 'Advanced', equipment: 'Kettlebell' },
  { name: 'Cable Anti-Rotation Press', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Cable' },
  { name: 'Resistance Band Pallof Press', target_muscle: 'Abs', category: 'Core', difficulty: 'Beginner', equipment: 'Equipment' },

  // FOREARMS
  { name: 'Wrist Curl', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Reverse Wrist Curl', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Dumbbell' },
  { name: 'Barbell Wrist Curl', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Reverse Barbell Wrist Curl', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Barbell' },
  { name: 'Farmers Walk', target_muscle: 'Forearms', category: 'Strongman', difficulty: 'Intermediate', equipment: 'Dumbbell' },
  { name: 'Plate Pinch', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Plate' },
  { name: 'Dead Hang', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Bodyweight' },
  { name: 'Towel Pull-Up', target_muscle: 'Forearms', category: 'Pull', difficulty: 'Advanced', equipment: 'Bodyweight' },
  { name: 'Gripper Exercise', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Equipment' },
  { name: 'Cable Wrist Curl', target_muscle: 'Forearms', category: 'Isolation', difficulty: 'Beginner', equipment: 'Cable' },
];

export default EXERCISE_SEED_DATA;
